<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">documentToPipeline</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:0:required document</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoNCgkvLyBkb2N1bWVudA0KCUlEYXRhCWRvY3VtZW50ID0gSURhdGFVdGlsLmdldElE
YXRhKCBwaXBlbGluZUN1cnNvciwgImRvY3VtZW50IiApOw0KCWlmICggZG9jdW1lbnQgIT0gbnVs
bCl7DQoJCUlEYXRhQ3Vyc29yIGRvY3VtZW50UGlwZWxpbmVDdXJzb3IgPSBkb2N1bWVudC5nZXRD
dXJzb3IoKTsNCgkJd2hpbGUoZG9jdW1lbnRQaXBlbGluZUN1cnNvci5uZXh0KCkpew0KCQkJT2Jq
ZWN0IG9iaiA9IGRvY3VtZW50UGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsNCgkJCWlmIChvYmog
PT0gbnVsbCkNCgkJICAgIHsNCgkJICAgICAgY29udGludWU7DQoJCSAgICB9DQoJCQ0KCQkgICAg
aWYgKG9iaiBpbnN0YW5jZW9mIFN0cmluZykNCgkJICAgIHsNCgkJICAgIAkNCgkJICAgICAgSURh
dGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgZG9jdW1lbnRQaXBlbGluZUN1cnNvci5nZXRLZXko
KSwgKFN0cmluZykgb2JqKTsgDQoJCSAgICB9DQoJCSAgICBlbHNlIGlmIChvYmogaW5zdGFuY2Vv
ZiBJRGF0YSkNCgkJICAgIHsNCgkJICAgICAgICBJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29y
LCBkb2N1bWVudFBpcGVsaW5lQ3Vyc29yLmdldEtleSgpLCAoSURhdGEpIG9iaik7DQoJCSAgICB9
DQoJCSAgICBlbHNlIGlmIChvYmogaW5zdGFuY2VvZiBJRGF0YVtdKQ0KCQkgICAgew0KCQkgICAg
ICAgIElEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsIGRvY3VtZW50UGlwZWxpbmVDdXJzb3Iu
Z2V0S2V5KCksIChJRGF0YVtdKSBvYmopOw0KCQkgICAgfQ0KCQkgICAgZWxzZQ0KCQkgICAgew0K
CQkgICAgICBJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCBkb2N1bWVudFBpcGVsaW5lQ3Vy
c29yLmdldEtleSgpLCBvYmopOw0KCQkgICAgfQ0KCQkJDQoJCX0NCgkJZG9jdW1lbnRQaXBlbGlu
ZUN1cnNvci5kZXN0cm95KCk7DQoJfQ0KDQoJDQoJDQoJcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Ow0KCQ0KCQ0K</value>
</Values>
