<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">caseTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required value</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVx
dWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBkZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkK
U3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Npb25JZCggcGlwZU1hcCApOwpTdHJpbmcgYWN0aW9u
ID0gZ2V0QWN0aW9uKCBwaXBlTWFwICk7ClN0cmluZyB0YWdTdmNOYW1lID0gZ2V0VGFnU3ZjTmFt
ZShwaXBlTWFwKTsKClN0cmluZyB2YWx1ZSA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJ2YWwiICk7
IC8vIENvbnN0YW50cy5WQUxVRV9QIApSZXBvcnRlciByZXBvcnRlciA9IEpTUE1hbmFnZXIuZ2V0
SW5zdGFuY2UoKS5nZXRSZXBvcnRlciggc2Vzc2lvbklkLHRhZ1N2Y05hbWUgKTsJClRlbXBsYXRl
VG9rZW4gdG9rZW4gPSBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tlbigg
c2Vzc2lvbklkLCB0YWdTdmNOYW1lICk7CgppZiAoIHJlcG9ydGVyID09IG51bGwgKSB7Cgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTWlzc2luZyByZXBvcnRlciBpbiBjYXNlIHRhZyEgTm8g
c3dpdGNoIHRhZyBpbiBqc3AgcGFnZT8iKTsKfQkJCQpyZXBvcnRlci5zZXRXcml0ZXIoIGdldFdy
aXRlciggcGlwZU1hcCApICk7CgppZiAoIGRlYnVnICkgewoJU3lzdGVtLmVyci5wcmludGxuKFN0
cmluZy5mb3JtYXQoIlxuWyVzXTolcyIsIHRhZ1N2Y05hbWUsIG5ldyBqYXZhLnV0aWwuRGF0ZSgp
KSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiUmVwb3J0ZXI6ICVzIiwgcmVw
b3J0ZXIpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJTZXNzaW9uSWQ6ICVz
Iiwgc2Vzc2lvbklkKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiYWN0aW9u
OiAlcyIsIGFjdGlvbikpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlZhcnM6
IHZhbD0lcyIsIHZhbHVlICkpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoImN1
cnJlbnRUb2tlbjogJXMiLCBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tl
bihzZXNzaW9uSWQsIHRhZ1N2Y05hbWUpKSk7Cn0KCgppZiAoIHRva2VuID09IG51bGwpIHsKCXRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJNaXNzaW5nIHN3aXRjaCB0b2tlbiBmb3Igc3dpdGNo
IHRhZyEiKTsKfQoKaWYgKCAhKHRva2VuIGluc3RhbmNlb2YgU3dpdGNoVG9rZW4pKSB7Cgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUGFyZW50IHRhZyBpcyBub3QgYSBzd2l0Y2ggdG9rZW4h
Iik7Cn0KCgppZiAoICJzdGFydCIuZXF1YWxzKGFjdGlvbikpIHsKCWJvb2xlYW4gbWF0Y2hlcyA9
ICgoU3dpdGNoVG9rZW4pdG9rZW4pLmdldE1hdGNoKCByZXBvcnRlciwgdmFsdWUpOwoJcGlwZU1h
cC5wdXQoICJtYXRjaGVzIiwgbWF0Y2hlcyk7IC8vQ29uc3RhbnRzLk1BVENIRVNfUAp9IGVsc2Ug
ewoJCn0KCg==</value>
</Values>
