<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">scopeTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required recordName</value>
    <value>[i] field:0:required options</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gWzBdIGZpZWxkOjA6cmVxdWlyZWQgdmFsaWQKCklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURh
dGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVxdWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBk
ZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkKU3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Np
b25JZCggcGlwZU1hcCApOwpTdHJpbmcgYWN0aW9uID0gZ2V0QWN0aW9uKCBwaXBlTWFwICk7ClN0
cmluZyB0YWdTdmNOYW1lID0gZ2V0VGFnU3ZjTmFtZShwaXBlTWFwKTsKClN0cmluZyByZWNvcmRO
YW1lID0gcGlwZU1hcC5nZXRBc1N0cmluZyggInJlY29yZE5hbWUiICk7IC8vIENvbnN0YW50cy5S
RUNPUkRfUApTdHJpbmcgb3B0aW9ucyA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJvcHRpb25zIiAp
OyAvLyBDb25zdGFudHMuT1BUSU9OU19QCgpKU1BTY29wZVRva2VuIHRva2VuID0gbnVsbDsKClJl
cG9ydGVyIHJlcG9ydGVyID0gSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLmdldFJlcG9ydGVyKHNl
c3Npb25JZCx0YWdTdmNOYW1lKTsKaWYgKCByZXBvcnRlciA9PSBudWxsICkgewoJcmVwb3J0ZXIg
PSBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuY3JlYXRlUmVwb3J0ZXIoc2Vzc2lvbklkLHRhZ1N2
Y05hbWUsIHJlcXVlc3QpOwp9CQkJCnJlcG9ydGVyLnNldFdyaXRlciggZ2V0V3JpdGVyKCBwaXBl
TWFwICkgKTsKCmlmICggZGVidWcgKSB7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1h
dCgiXG5bJXNdOiVzIiwgdGFnU3ZjTmFtZSwgbmV3IGphdmEudXRpbC5EYXRlKCkpKTsKCVN5c3Rl
bS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJSZXBvcnRlcjogJXMiLCByZXBvcnRlcikpOwoJ
U3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlNlc3Npb25JZDogJXMiLCBzZXNzaW9u
SWQpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJhY3Rpb246ICVzIiwgYWN0
aW9uKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiVmFyczogcmVjb3JkTmFt
ZT0lcywgb3B0aW9ucz0lcyIsIHJlY29yZE5hbWUsIG9wdGlvbnMgKSk7CglTeXN0ZW0uZXJyLnBy
aW50bG4oU3RyaW5nLmZvcm1hdCgiY3VycmVudFRva2VuOiAlcyIsIEpTUE1hbmFnZXIuZ2V0SW5z
dGFuY2UoKS5nZXRUZW1wbGF0ZVRva2VuKHNlc3Npb25JZCx0YWdTdmNOYW1lKSkpOwp9CgoKCmlm
ICggInN0YXJ0Ii5lcXVhbHMoYWN0aW9uKSkgewoJdG9rZW4gPSBuZXcgSlNQU2NvcGVUb2tlbigg
cmVjb3JkTmFtZSwgb3B0aW9ucyApOwoJdG9rZW4uZXZhbChyZXBvcnRlcik7CglKU1BNYW5hZ2Vy
LmdldEluc3RhbmNlKCkudXBkYXRlVG9rZW4oIHNlc3Npb25JZCx0YWdTdmNOYW1lLCB0b2tlbik7
CglwaXBlTWFwLnB1dCggInZhbGlkIiwgdG9rZW4uaXNWYWxpZCgpICk7IC8vIENvbnN0YW50cy5W
QUxJRF9QCgp9IGVsc2UgewoJdG9rZW4gPSAoSlNQU2NvcGVUb2tlbilKU1BNYW5hZ2VyLmdldElu
c3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsdGFnU3ZjTmFtZSk7Cgl0b2tlbi5l
bmQoIHJlcG9ydGVyICk7Cn0KCg==</value>
</Values>
