<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invokeTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required username</value>
    <value>[i] field:0:required fullSvcName</value>
    <value>[i] field:0:required newPipe</value>
    <value>[i] field:0:required writer</value>
    <value>[i] field:0:required action</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required errorMessage</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAJCgpJRGF0YU1hcCBwaXBlTWFwID0gbmV3IElEYXRhTWFwKHBpcGVsaW5lKTsJCQkJCklEYXRh
IHJlcXVlc3QgPSBwaXBlbGluZTsKCmJvb2xlYW4gZGVidWcgPSBnZXREZWJ1ZyggcGlwZU1hcCAp
OwkJClN0cmluZyBzZXNzaW9uSWQgPSBnZXRTZXNzaW9uSWQoIHBpcGVNYXAgKTsKU3RyaW5nIGFj
dGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCApOwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRhZ1N2
Y05hbWUocGlwZU1hcCk7CgoKU3RyaW5nIHVzZXJuYW1lID0gcGlwZU1hcC5nZXRBc1N0cmluZygi
dXNlcm5hbWUiKTsgLy9Db25zdGFudHMuS0VZX1BJUEVMSU5FX1VTRVJOQU1FClN0cmluZyBmdWxs
U3ZjTmFtZSA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoImZ1bGxTdmNOYW1lIik7Ly9Db25zdGFudHMu
S0VZX1BJUEVMSU5FX1NFUlZJQ0VOQU1FCklEYXRhIG5ld1BpcGUgPSBwaXBlTWFwLmdldEFzSURh
dGEoIm5ld1BpcGUiKTsKaWYgKG5ld1BpcGUgPT0gbnVsbCkgewoJSURhdGFNYXAgbSA9IG5ldyBJ
RGF0YU1hcCgpOwoJbmV3UGlwZSA9IG0uZ2V0SURhdGEoKTsKfQppZiAoIGZ1bGxTdmNOYW1lID09
IG51bGwgfHwgZnVsbFN2Y05hbWUubGVuZ3RoKCkgPT0gMCApIHsKICAgIFNlcnZlci5sb2dFcnJv
cigoU3RyaW5nKW51bGwsICJzZXJ2aWNlSW50ZXJmYWNlL05hbWUgaW5wdXRzIGFyZSByZXF1aXJl
ZCIpOwogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInNlcnZpY2VJbnRlcmZhY2UvTmFt
ZSBpbnB1dHMgYXJlIHJlcXVpcmVkIGZvciBpbnZva2VUYWdTZXJ2aWNlIik7Cn0KClJlcG9ydGVy
IHJlcG9ydGVyID0gSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLmdldFJlcG9ydGVyKHNlc3Npb25J
ZCx0YWdTdmNOYW1lKTsKaWYgKCByZXBvcnRlciA9PSBudWxsICkgewoJcmVwb3J0ZXIgPSBKU1BN
YW5hZ2VyLmdldEluc3RhbmNlKCkuY3JlYXRlUmVwb3J0ZXIoc2Vzc2lvbklkLHRhZ1N2Y05hbWUs
IHJlcXVlc3QpOwp9CQkJCnJlcG9ydGVyLnNldFdyaXRlciggZ2V0V3JpdGVyKCBwaXBlTWFwICkg
KTsKCmlmICggZGVidWcgKSB7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiXG5b
JXNdOiVzIiwgdGFnU3ZjTmFtZSwgbmV3IGphdmEudXRpbC5EYXRlKCkpKTsKCVN5c3RlbS5lcnIu
cHJpbnRsbihTdHJpbmcuZm9ybWF0KCJSZXBvcnRlcjogJXMiLCByZXBvcnRlcikpOwoJU3lzdGVt
LmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlNlc3Npb25JZDogJXMiLCBzZXNzaW9uSWQpKTsK
CVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJhY3Rpb246ICVzIiwgYWN0aW9uKSk7
CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiVmFyczogdXNlcm5hbWU9JXMsIGZ1
bGxTdmNOYW1lPSVzLCBuZXdQaXBlPSVzIiwgdXNlcm5hbWUsIGZ1bGxTdmNOYW1lLCBuZXdQaXBl
ICkpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoImN1cnJlbnRUb2tlbjogJXMi
LCBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsdGFn
U3ZjTmFtZSkpKTsKfQogICAKCiAKSlNQSW52b2tlVG9rZW4gdG9rZW4gPSBudWxsOwoKaWYgKCAi
c3RhcnQiLmVxdWFscyhhY3Rpb24pKSB7CgoJdG9rZW4gPSBuZXcgSlNQSW52b2tlVG9rZW4oTlNO
YW1lLmNyZWF0ZShmdWxsU3ZjTmFtZSkpOwoJCgkvLyBzZXQgdXAgdGhlIEludm9rZVN0YXRlCglJ
bnZva2VTdGF0ZSBzdGF0ZSA9IGluaXRpYWxpemVJbnZva2VTdGF0ZSgpOwoJaWYgKCBJbnZva2VT
dGF0ZS5nZXRDdXJyZW50VXNlcigpID09IG51bGwpIHsKCQoJCVVzZXIgdXNlciA9IFVzZXJNYW5h
Z2VyLmdldFVzZXIodXNlcm5hbWUpOwoJCUludm9rZVN0YXRlLnNldEN1cnJlbnRVc2VyKCB1c2Vy
ICk7Cgl9CgkKCgkvLyBldmFsdWF0ZSB0aGUgdG9rZW4KCS8vIHRoZSBzZXJ2aWNlIGludm9jYXRp
b24gaGFwcGVucyBoZXJlCgl0b2tlbi5ldmFsKHJlcG9ydGVyKTsKCUpTUE1hbmFnZXIuZ2V0SW5z
dGFuY2UoKS51cGRhdGVUb2tlbiggc2Vzc2lvbklkLHRhZ1N2Y05hbWUsIHRva2VuKTsKCQkJCQkJ
CglpZiAoIHRva2VuLmlzRXJyb3IoKSkgewoJCXBpcGVNYXAucHV0KCIkZXJyb3IiLCB0cnVlKTsg
Ly8gQ29uc3RhbnRzLklTX0VSUk9SX1AKCQlwaXBlTWFwLnB1dCgiJGVycm9yTWVzc2FnZSIsIHRv
a2VuLmdldEVycm9yTWVzc2FnZSgpKTsgLy8gQ29uc3RhbnRzLkVSUk9SX01FU1NBR0VfUAoJfQoJ
ICAgIAp9IGVsc2UgaWYgKCAiZW5kIi5lcXVhbHMoYWN0aW9uKSkgewoJdG9rZW4gPSAoSlNQSW52
b2tlVG9rZW4pSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLmdldFRlbXBsYXRlVG9rZW4oc2Vzc2lv
bklkLHRhZ1N2Y05hbWUpOwoJdG9rZW4uZW5kKHJlcG9ydGVyKTsKCglpZiAoIHRva2VuLmlzRXJy
b3IoKSkgewoJCXBpcGVNYXAucHV0KCIkZXJyb3IiLCB0cnVlKTsgLy8gQ29uc3RhbnRzLklTX0VS
Uk9SX1AKCQlwaXBlTWFwLnB1dCgiJGVycm9yTWVzc2FnZSIsIHRva2VuLmdldEVycm9yTWVzc2Fn
ZSgpKTsgLy8gQ29uc3RhbnRzLkVSUk9SX01FU1NBR0VfUAoJfQoKfQkJCgkJCQo=</value>
</Values>
